FROM --platform=linux/amd64 rust:1.85-bookworm AS builder

WORKDIR /app
COPY . .

RUN CARGO_PROFILE_RELEASE_LTO=false \
    CARGO_PROFILE_RELEASE_CODEGEN_UNITS=16 \
    CARGO_BUILD_JOBS=2 \
    cargo build -p tls-probe --release

FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/ubi-minimal:latest

COPY --from=builder /app/target/release/tls-probe /usr/local/bin/tls-probe

ENTRYPOINT ["tls-probe"]
CMD ["listeners"]
