[package]
name = "tls-probe-common"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Shared types between eBPF probes and userspace"

[features]
default = []
user = ["dep:aya"]

[dependencies]

[target.'cfg(target_os = "linux")'.dependencies]
aya = { workspace = true, optional = true }

[lib]
path = "src/lib.rs"
